version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    depends_on:
      - db
    volumes:
      - .:/www/public

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: feedvote
      MYSQL_PASSWORD: olugbenga
      MYSQL_ROOT_PASSWORD: olugbenga
      MYSQL_USER: kastroud
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.1.1-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
